services:
  app:
    image: platform-athenas:x86
    container_name: platform-athenas
    ports:
      - "5001"
    networks:
      - app_network
    volumes:
      - .:/src
    working_dir: /src
    env_file:
      - .env
    command: ["gunicorn", "-w", "4", "-b", "0.0.0.0:5001", "src.app:create_app"]
    platform: linux/amd64

networks:
  app_network:
    driver: bridge