version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: platform-athenas
    ports:
      - "8080:8080"
    networks:
      - app_network
    env_file:
      - .env
    command: ["gunicorn", "-w", "4", "-b", "0.0.0.0:8080", "src.app:create_app()"]
    platform: linux/amd64

networks:
  app_network:
    driver: bridge