services:
  app:
    image: athenas:x86
    container_name: athenas-dev
    ports:
      - "${DEV_PORT}:${DEV_PORT}"
    networks:
      - app_network
    volumes:
      - .:/src
    working_dir: /src
    env_file:
      - .env
    command: ["gunicorn", "-w", "4", "-b", "0.0.0.0:${DEV_PORT}", "app:create_app()"]

networks:
  app_network:
    driver: bridge